# Generated by Django 5.2 on 2025-12-23 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('our_story', models.TextField()),
                ('our_mission', models.TextField()),
                ('our_vision', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Addmission_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_first_name', models.CharField(max_length=20)),
                ('student_last_name', models.CharField(max_length=20)),
                ('student_last_gender', models.CharField(max_length=20)),
                ('student_date_of_birth', models.CharField(max_length=20)),
                ('grade_applying_for', models.CharField(max_length=20)),
                ('previous_school', models.CharField(max_length=120)),
                ('Guardian_name', models.CharField(max_length=20)),
                ('Guardian_relation', models.CharField(max_length=60)),
                ('Guardian_email', models.EmailField(max_length=254)),
                ('Guardian_mobile', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('comments', models.TextField()),
                ('seen', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Blog_Item',
            fields=[
                ('id', models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=80)),
                ('image', models.ImageField(upload_to='media/Blog')),
                ('descreption', models.TextField()),
                ('Author_name', models.CharField(max_length=80)),
                ('date_time', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Contact_querries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.TextField()),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Gallery_Item',
            fields=[
                ('id', models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('video_link', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Notice_Items',
            fields=[
                ('id', models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=80)),
                ('descreption', models.CharField(max_length=80)),
                ('Author_name', models.CharField(max_length=80)),
                ('date_time', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Official_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Header', models.CharField(max_length=80)),
                ('address', models.CharField(max_length=80)),
                ('mobile_primary', models.CharField(max_length=10)),
                ('mobile_secondary', models.CharField(max_length=10)),
                ('email_primary', models.EmailField(max_length=254)),
                ('email_secondary', models.EmailField(max_length=254)),
                ('map_link', models.TextField()),
                ('whats_app_mobile', models.CharField(max_length=10)),
                ('whatsapp_message', models.TextField()),
                ('logo', models.ImageField(upload_to='media/logo')),
                ('Hero_Video', models.ImageField(upload_to='media/Hero_video')),
            ],
        ),
        migrations.CreateModel(
            name='Pride_Of_students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('Designation', models.CharField(max_length=80)),
            ],
        ),
    ]
