# Generated by Django 5.2 on 2025-12-26 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact_querries',
            old_name='mobile',
            new_name='phone',
        ),
    ]
