# Generated by Django 5.2 on 2025-12-26 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_mobile_contact_querries_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home_page_stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years_of_excellence', models.CharField(max_length=5)),
                ('Happy_Students', models.CharField(max_length=5)),
                ('Success_Rate', models.CharField(max_length=5)),
                ('Expert_Teachers', models.CharField(max_length=5)),
            ],
        ),
        migrations.AlterField(
            model_name='addmission_form',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
