# Generated by Django 5.2 on 2025-12-26 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_home_page_stats_alter_addmission_form_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel_Items_students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='media/carousel/')),
                ('Title', models.CharField(max_length=50)),
            ],
        ),
    ]
