# Generated by Django 5.2 on 2025-12-27 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_carousel_items_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='official_detail',
            name='session_year',
            field=models.CharField(default='2025-2026', max_length=80),
        ),
    ]
