# Generated by Django 5.2 on 2025-12-27 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_official_detail_session_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='admission_proces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='important_date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='required_document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='values_section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('message', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='official_detail',
            name='facebook',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='official_detail',
            name='instagram',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='official_detail',
            name='youtube',
            field=models.TextField(default=''),
        ),
    ]
