# Generated by Django 5.2 on 2025-12-28 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_admission_proces_important_date_required_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_page',
            name='about_image',
            field=models.ImageField(default='default.png', upload_to='aboutImage'),
        ),
    ]
