# Generated by Django 5.2 on 2025-12-28 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_about_page_about_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about_page',
            name='our_story',
        ),
        migrations.AddField(
            model_name='about_page',
            name='our_story_1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='about_page',
            name='our_story_2',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='about_page',
            name='our_mission',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='about_page',
            name='our_vision',
            field=models.TextField(blank=True),
        ),
    ]
