# Generated by Django 5.2 on 2025-12-28 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_about_page_our_story_about_page_our_story_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='home_page_stats',
            name='Hero_video',
            field=models.FileField(default='default.mp4', upload_to='Hero_video_Home'),
        ),
    ]
