# Generated by Django 5.2 on 2025-12-28 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_home_page_stats_hero_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='home_page_stats',
            name='About_Image',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='home_page_stats',
            name='About_Text',
            field=models.TextField(default=''),
        ),
    ]
