# Generated by Django 5.2 on 2025-12-28 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_home_page_stats_about_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home_Why_Choose_Us',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=80)),
                ('text', models.TextField()),
            ],
        ),
    ]
