# Generated by Django 5.2 on 2025-12-28 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_admission_proces_id_alter_important_date_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='important_date',
            name='tittle',
            field=models.CharField(default='', max_length=40),
        ),
    ]
