# Generated by Django 5.2 on 2025-12-28 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_admission_proces_id_alter_important_date_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery_item',
            name='Title',
            field=models.CharField(default='', max_length=80),
        ),
    ]
