# Generated by Django 5.2 on 2025-12-28 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_gallery_item_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Office_Hours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=80)),
                ('timing', models.CharField(max_length=120)),
            ],
        ),
    ]
