# Generated by Django 5.2 on 2025-12-28 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_office_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addmission_form',
            name='address',
        ),
        migrations.AddField(
            model_name='addmission_form',
            name='street',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='addmission_form',
            name='Guardian_email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='addmission_form',
            name='Guardian_mobile',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='addmission_form',
            name='Guardian_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='addmission_form',
            name='Guardian_relation',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='addmission_form',
            name='comments',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='addmission_form',
            name='grade_applying_for',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='addmission_form',
            name='previous_school',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='addmission_form',
            name='student_date_of_birth',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='addmission_form',
            name='student_first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='addmission_form',
            name='student_last_gender',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='addmission_form',
            name='student_last_name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
