# Generated by Django 5.2 on 2025-12-28 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_remove_addmission_form_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addmission_form',
            old_name='street',
            new_name='address',
        ),
    ]
