# Generated by Django 5.2 on 2025-12-28 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_rename_street_addmission_form_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='official_detail',
            name='address',
        ),
        migrations.AddField(
            model_name='official_detail',
            name='city',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='official_detail',
            name='country',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='official_detail',
            name='state',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='official_detail',
            name='street',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='official_detail',
            name='Header',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='official_detail',
            name='Hero_Video',
            field=models.ImageField(default='', upload_to='media/Hero_video'),
        ),
        migrations.AlterField(
            model_name='official_detail',
            name='email_primary',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='official_detail',
            name='email_secondary',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='official_detail',
            name='logo',
            field=models.ImageField(default='', upload_to='media/logo'),
        ),
        migrations.AlterField(
            model_name='official_detail',
            name='map_link',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='official_detail',
            name='mobile_primary',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='official_detail',
            name='mobile_secondary',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='official_detail',
            name='whats_app_mobile',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='official_detail',
            name='whatsapp_message',
            field=models.TextField(default=''),
        ),
    ]
