# Generated by Django 5.2 on 2025-12-28 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_remove_official_detail_address_official_detail_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='official_detail',
            name='pincode',
            field=models.CharField(default='', max_length=8),
        ),
    ]
