# Generated by Django 5.2 on 2025-12-28 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_official_detail_pincode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='official_detail',
            name='Hero_Video',
        ),
        migrations.AlterField(
            model_name='official_detail',
            name='mobile_primary',
            field=models.CharField(default='', max_length=14),
        ),
        migrations.AlterField(
            model_name='official_detail',
            name='mobile_secondary',
            field=models.CharField(default='', max_length=14),
        ),
        migrations.AlterField(
            model_name='official_detail',
            name='whats_app_mobile',
            field=models.CharField(default='', max_length=14),
        ),
    ]
