# Generated by Django 5.2 on 2025-12-28 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_remove_official_detail_hero_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='official_detail',
            name='mail_message',
            field=models.TextField(default=''),
        ),
    ]
