# Generated by Django 5.2 on 2025-12-28 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_official_detail_mail_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='official_detail',
            name='footer_quote',
            field=models.CharField(default='Empowering future leaders through quality education with love and care', max_length=120),
        ),
        migrations.AddField(
            model_name='official_detail',
            name='school_name',
            field=models.CharField(default='Gyanodaya Public School', max_length=120),
        ),
    ]
