# Generated by Django 5.2 on 2025-12-28 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_official_detail_footer_quote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_item',
            name='catigory',
            field=models.CharField(default='Education', max_length=80),
        ),
        migrations.AddField(
            model_name='blog_item',
            name='headline',
            field=models.CharField(default='Our Annual Sports Day was a spectacular event showcasing the athletic talents of our students across various competitions and games.', max_length=80),
        ),
    ]
